def exceptionResponse(inst):
    print("Something goes wrong, try again later. The error description: \n\n")
    print(type(inst))
    print(inst.args)   
    print(inst)    
